version: '2'
services:

  elasticsearch:
    image: elasticsearch:1.7

  django:
    links:
      - elasticsearch
    environment:
      - REGISTRY_SEARCH_URL=elasticsearch+http://elasticsearch:9200

  celery:
    links:
      - elasticsearch
    environment:
      - REGISTRY_SEARCH_URL=elasticsearch+http://elasticsearch:9200
